# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x, 20.x]
        command: ['lint', 'format', 'test', 'build']
    steps:
      - uses: actions/checkout@v3

      - name: Set Up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable --immutable-cache

      - run: yarn ${{ matrix.command }}
